apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kz49fmt0b-python 
  janus-idp.io/tekton: kz49fmt0b-python
  backstage.io/kubernetes-id: kz49fmt0b-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kz49fmt0b-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml